#!/usr/bin/env node
'use strict';

/**
 * Generate Third-Party Notices
 * ============================================================================
 * Generates the npm dependency section of THIRD-PARTY-NOTICES using
 * license-checker. Appends/replaces Section 3 content while preserving
 * manually curated Sections 1, 2, and 4.
 *
 * Usage: node scripts/generate-notices.js
 *
 * Runs license-checker without --production to capture devDependencies
 * that are bundled by esbuild (e.g., json-formatter-js).
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// ============================================================================
// Configuration
// ============================================================================

const NOTICES_PATH = path.join(__dirname, '..', '..', 'THIRD-PARTY-NOTICES');
const SECTION_3_HEADER = 'SECTION 3: FULL NPM DEPENDENCY LICENSES';
const SECTION_4_HEADER = 'SECTION 4: RUNTIME SERVICES';

// ============================================================================
// Run license-checker
// ============================================================================

function getLicenseData() {
  try {
    const raw = execSync('npx license-checker --json --relativeLicensePath', {
      cwd: path.join(__dirname, '..'),
      encoding: 'utf-8',
      maxBuffer: 10 * 1024 * 1024,
    });
    return JSON.parse(raw);
  } catch (err) {
    console.error('Failed to run license-checker:', err.message);
    process.exit(1);
  }
}

// ============================================================================
// Analyze and format
// ============================================================================

function formatLicenseData(data) {
  const entries = Object.entries(data);
  const lines = [];

  // Summary counts
  const licenseCounts = {};
  for (const [, info] of entries) {
    const license = info.licenses || 'UNKNOWN';
    licenseCounts[license] = (licenseCounts[license] || 0) + 1;
  }

  // Sort by frequency
  const sorted = Object.entries(licenseCounts).sort((a, b) => b[1] - a[1]);

  lines.push(`Total packages: ${entries.length}`);
  lines.push('');
  lines.push('License distribution:');
  for (const [license, count] of sorted) {
    lines.push(`  ${license}: ${count}`);
  }

  // GPL check
  const gplPackages = entries.filter(([, info]) => {
    const lic = (info.licenses || '').toUpperCase();
    return lic.includes('GPL') && !lic.includes('LGPL') && !lic.includes('MPL');
  });

  lines.push('');
  if (gplPackages.length === 0) {
    lines.push('Zero GPL-licensed packages. Zero AGPL-licensed packages.');
  } else {
    lines.push(`WARNING: ${gplPackages.length} GPL-licensed package(s) detected:`);
    for (const [name] of gplPackages) {
      lines.push(`  - ${name}`);
    }
  }

  lines.push('');
  lines.push('Per-package listing:');
  lines.push('');

  // Per-package detail
  for (const [pkg, info] of entries.sort(([a], [b]) => a.localeCompare(b))) {
    const license = info.licenses || 'UNKNOWN';
    const publisher = info.publisher || '';
    const repo = info.repository || '';
    lines.push(`  ${pkg}`);
    lines.push(`    License: ${license}`);
    if (publisher) lines.push(`    Publisher: ${publisher}`);
    if (repo) lines.push(`    Repository: ${repo}`);
  }

  return lines.join('\n');
}

// ============================================================================
// Splice into THIRD-PARTY-NOTICES
// ============================================================================

function updateNoticesFile(formattedData) {
  if (!fs.existsSync(NOTICES_PATH)) {
    console.error(`THIRD-PARTY-NOTICES not found at: ${NOTICES_PATH}`);
    console.error('Create it first with the curated sections, then run this script.');
    process.exit(1);
  }

  const content = fs.readFileSync(NOTICES_PATH, 'utf-8');

  // Find Section 3 boundaries
  const s3Start = content.indexOf(SECTION_3_HEADER);
  const s4Start = content.indexOf(SECTION_4_HEADER);

  if (s3Start === -1 || s4Start === -1) {
    console.error('Could not find Section 3 or Section 4 markers in THIRD-PARTY-NOTICES.');
    process.exit(1);
  }

  // Find the line after the Section 3 separator (================)
  const s3SeparatorEnd = content.indexOf('\n', content.indexOf('====', s3Start + SECTION_3_HEADER.length)) + 1;

  // Find the line of the Section 4 separator (================) — go back from SECTION_4_HEADER
  const beforeS4 = content.lastIndexOf('================', s4Start);
  const s4BlockStart = content.lastIndexOf('\n', beforeS4) + 1;

  // Build replacement
  const before = content.substring(0, s3SeparatorEnd);
  const after = content.substring(s4BlockStart);

  const newSection3 = [
    '',
    'This section is auto-generated by running:',
    '  node scripts/generate-notices.js',
    '',
    'from the aether-frontend directory.',
    '',
    formattedData,
    '',
  ].join('\n');

  const updated = before + newSection3 + after;

  fs.writeFileSync(NOTICES_PATH, updated, 'utf-8');
  console.log(`Updated ${NOTICES_PATH}`);
}

// ============================================================================
// Main
// ============================================================================

console.log('Running license-checker (all dependencies)...');
const data = getLicenseData();
console.log(`Found ${Object.keys(data).length} packages.`);

const formatted = formatLicenseData(data);
updateNoticesFile(formatted);

console.log('Done.');
