/**
Incoming: storageAPI.loadArtifacts(), IPC stream payloads --- {Dict, json}
Processing: Normalize artifact fields (streaming or persisted), hydrate metadata, derive missing fields --- {3 jobs: JOB_NORMALIZE, JOB_VALIDATE_SCHEMA, JOB_DERIVE_FIELDS}
Outgoing: ArtifactSessionManager, FileManager consumers --- {Dict, object}

CONTRACT NOTES:
- Streaming artifacts (WebSocket): Have role, executionGroup, format, request_id, timestamp
- Persisted artifacts (Database): Have type, artifact_id, chat_id, created_at (NO role, executionGroup, format, request_id)
- This normalizer handles BOTH by deriving missing fields for persisted artifacts
*/

'use strict';

function normalizeArtifactPayload(rawArtifact = {}, fallbackChatId = null) {
  if (!rawArtifact || typeof rawArtifact !== 'object') {
    throw new Error('[ArtifactNormalizer] CONTRACT VIOLATION: rawArtifact must be a non-null object');
  }

  const metadata = rawArtifact.metadata && typeof rawArtifact.metadata === 'object'
    ? { ...rawArtifact.metadata }
    : {};

  // DISTINGUISH: Streaming vs Persisted artifacts
  // Streaming artifacts have: role, execution_group, format, request_id, timestamp (from WebSocket)
  // Persisted artifacts have: id (UUID), created_at (from database load)
  // NOTE: User-uploaded files ARE persisted but MAY have role in metadata
  // RELIABLE INDICATORS: PostgreSQL UUID format (id field) or created_at timestamp
  //
  // CRITICAL FIX: Check BOTH snake_case (created_at) AND camelCase (createdAt)
  // Some API clients or middleware might transform response keys
  const hasPostgresqlId = rawArtifact.id && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(rawArtifact.id);
  const isPersistedArtifact = hasPostgresqlId || !!rawArtifact.created_at || !!rawArtifact.createdAt;

  // TYPE: Always required (present in both streaming and persisted)
  const type = rawArtifact.type || rawArtifact.kind || metadata.type;
  if (!type || typeof type !== 'string') {
    throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: type is required. artifact_id=${rawArtifact.artifact_id || rawArtifact.id || 'unknown'}`);
  }
  const typeLower = type.toLowerCase();
  const isAttachment = typeLower === 'file';

  // ROLE: Required for streaming, DERIVED for persisted
  let role = rawArtifact.role || metadata.role;
  if (!role) {
    if (isPersistedArtifact) {
      // Derive role from type for persisted artifacts
      role = _deriveRoleFromType(type);
    } else {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: role is required for streaming artifacts. artifact_id=${rawArtifact.artifact_id || rawArtifact.id || 'unknown'}`);
    }
  }

  // ID HANDLING: Distinguish PostgreSQL UUID vs frontend artifact_id
  // - Persisted artifacts have: id (UUID from backend) + artifact_id (frontend dedup key)
  // - Streaming artifacts have: artifact_id only (generated by frontend during streaming)
  // - Backend DELETE/UPDATE operations require the PostgreSQL UUID (id field)
  // - Frontend deduplication uses artifact_id
  const postgresqlUuid = isPersistedArtifact && rawArtifact.id ? rawArtifact.id : null;
  const artifactId = rawArtifact.artifact_id || rawArtifact.id || metadata.frontend_id || metadata.frontendId;
  if (!artifactId || typeof artifactId !== 'string') {
    throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: artifact_id or id is required. role=${role}, type=${type}`);
  }

  // REQUEST_ID: Required for streaming, DERIVED for persisted
  let requestId = rawArtifact.request_id || rawArtifact.requestId || metadata.request_id || metadata.requestId;
  if (!requestId) {
    if (isPersistedArtifact) {
      // Derive request_id from artifact_id for persisted artifacts (extract base UUID)
      requestId = _deriveRequestIdFromArtifactId(artifactId);
    } else {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: request_id is required for streaming artifacts. artifact_id=${artifactId}, role=${role}, type=${type}`);
    }
  }

  // CHAT_ID: Always required (or fallback provided)
  const chatId = rawArtifact.chatId || rawArtifact.chat_id || metadata.chatId || metadata.chat_id || fallbackChatId;
  if (!chatId || typeof chatId !== 'string') {
    throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: chatId is required. artifact_id=${artifactId}, requestId=${requestId}`);
  }

  // EXECUTION_GROUP: Required for code/output artifacts (streaming AND persisted)
  // Persisted artifacts may not store execution_group explicitly in top-level fields; 
  // check metadata first, then derive from artifact_id if missing.
  let executionGroup =
    rawArtifact.executionGroup ||
    rawArtifact.execution_group ||
    metadata.executionGroup ||
    metadata.execution_group ||
    null;

  if (!executionGroup && !isAttachment) {
    if (isPersistedArtifact) {
      // ARCHITECTURAL FIX: For multi-execution turns, multiple execution groups share the same requestId.
      // We must check if artifact_id contains a unique counter or identifier.
      // For legacy artifacts without execution_group, falling back to requestId is acceptable.
      executionGroup = metadata.execution_group || metadata.executionGroup || requestId;
    } else {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: executionGroup is required for streaming artifacts. artifact_id=${artifactId}, requestId=${requestId}, chatId=${chatId}`);
    }
  }

  // FORMAT: Required for streaming, DERIVED for persisted
  let format = rawArtifact.format || metadata.format;
  if (!format) {
    if (isPersistedArtifact) {
      // Derive format from type and language for persisted artifacts
      format = _deriveFormatFromType(type, rawArtifact.language);
    } else {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: format is required for streaming artifacts. artifact_id=${artifactId}, requestId=${requestId}`);
    }
  }

  // Optional fields - require explicit values or null
  const language = rawArtifact.language || metadata.language || null;
  const messageId = rawArtifact.messageId || rawArtifact.message_id || metadata.messageId || metadata.message_id || null;
  const parentId = rawArtifact.parentId || rawArtifact.parent_id || metadata.parentId || metadata.parent_id || null;
  const correlationId = rawArtifact.correlationId || rawArtifact.correlation_id || metadata.correlationId || metadata.correlation_id || null;

  // FILENAME: Required for attachments; derived for code/output when missing
  let filename = rawArtifact.filename || metadata.filename || null;
  if (!filename) {
    if (isAttachment) {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: filename is required for file artifacts. artifact_id=${artifactId}, requestId=${requestId}`);
    }
    filename = _deriveFilename(role, typeLower, format, language);
  }
  
  // TIMESTAMP: Required for streaming, DERIVED from created_at for persisted
  let timestamp = rawArtifact.timestamp || metadata.timestamp;
  if (!timestamp || typeof timestamp !== 'number' || timestamp <= 0) {
    if (isPersistedArtifact && (rawArtifact.created_at || rawArtifact.createdAt)) {
      // Convert created_at/createdAt (ISO string or Date) to Unix timestamp
      // DEFENSIVE: Check both snake_case and camelCase variants
      const createdAtField = rawArtifact.created_at || rawArtifact.createdAt;
      const createdAt = typeof createdAtField === 'string' 
        ? new Date(createdAtField) 
        : createdAtField;
      timestamp = createdAt instanceof Date ? createdAt.getTime() : Date.now();
    } else {
      throw new Error(`[ArtifactNormalizer] CONTRACT VIOLATION: timestamp must be a positive number. artifact_id=${artifactId}, requestId=${requestId}`);
    }
  }

  // CONTRACT: Content must be string (can be empty)
  const content = typeof rawArtifact.content === 'string' ? rawArtifact.content : (typeof metadata.content === 'string' ? metadata.content : '');
  
  const category = rawArtifact.category || metadata.category || null;

  const normalized = {
    ...rawArtifact,
    metadata,
    id: artifactId,                    // ALWAYS use artifact_id for deduplication
    postgresqlId: postgresqlUuid,      // Store PostgreSQL UUID separately for backend operations
    artifactId: artifactId,            // Frontend dedup key
    request_id: requestId,
    requestId: requestId,
    executionGroup: executionGroup,
    filename: filename,
    role: role.toLowerCase(),
    type: typeLower,
    format: format,
    language: language,
    chatId: chatId,
    messageId: messageId,
    parentId: parentId,
    correlationId: correlationId,
    timestamp: timestamp,
    content: content,
    category: category,
  };

  return normalized;
}

/**
 * Derive role from artifact type
 * @private
 */
function _deriveRoleFromType(type) {
  // Map artifact types to roles based on architectural contracts
  const typeToRoleMap = {
    'code': 'assistant',
    'html': 'assistant',
    'markdown': 'assistant',
    'text': 'assistant',
    'json': 'assistant',
    'file': 'user',         // User-uploaded files default to user role
    'output': 'computer',
    'console': 'computer'
  };
  return typeToRoleMap[type.toLowerCase()] || 'assistant';
}

/**
 * Derive request_id from artifact_id
 * Persisted artifacts have artifact_id like "uuid:code:1" or "uuid:output:2"
 * Extract base UUID as request_id
 * @private
 */
function _deriveRequestIdFromArtifactId(artifactId) {
  if (!artifactId || typeof artifactId !== 'string') {
    throw new Error('[ArtifactNormalizer] CONTRACT VIOLATION: artifactId must be a string to derive request_id');
  }
  
  // File attachments use formats like "file:timestamp:random"
  if (artifactId.startsWith('file:')) {
    return artifactId;
  }
  
  // Extract UUID portion (before first colon if composite, or full string if UUID)
  const parts = artifactId.split(':');
  if (parts.length > 0) {
    const candidate = parts[0];
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(candidate);
    if (!isUuid) {
      // Robust fallback instead of crashing the UI stream
      return artifactId;
    }
    return candidate;
  }
  
  return artifactId;
}

/**
 * Derive format from type and language
 * @private
 */
function _deriveFormatFromType(type, language) {
  const typeNormalized = type ? type.toLowerCase() : 'text';
  
  // Map types to formats
  const typeToFormatMap = {
    'code': language || 'text',
    'html': 'html',
    'markdown': 'markdown',
    'text': 'text',
    'json': 'json',
    'file': language || 'text',
    'output': 'text',
    'console': 'text'
  };
  
  return typeToFormatMap[typeNormalized] || 'text';
}

/**
 * Derive deterministic filename when missing.
 * @private
 */
function _deriveFilename(role, type, format, language) {
  const safeFormat = (format || language || 'txt').toString().toLowerCase();
  const safeType = (type || 'artifact').toString().toLowerCase();
  const safeRole = (role || 'artifact').toString().toLowerCase();

  if (safeRole === 'assistant' && safeType === 'code') {
    return `code.${safeFormat}`;
  }
  if (safeRole === 'computer' && safeType === 'output') {
    return `output.${safeFormat}`;
  }
  if (safeRole === 'computer' && safeType === 'console') {
    return 'console.log';
  }
  if (safeType === 'html') {
    return 'output.html';
  }
  return `${safeType}.${safeFormat}`;
}

module.exports = {
  normalizeArtifactPayload,
};
