import time
import asyncio
import sqlite3
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict

from db_handler import SimulationDBHandler

@dataclass
class SimulationScenario:
    """Represents a single simulation scenario."""
    name: str
    description: str
    emails: List[Dict[str, str]] = field(default_factory=list)
    browser_logs: List[Dict[str, str]] = field(default_factory=list)
    fs_logs: List[Dict[str, str]] = field(default_factory=list)

class SimulationRunner:
    """Orchestrates the simulation, handles DB injections, and monitors results."""
    
    def __init__(self, workspace_root: Path):
        from config.settings import get_settings
        self.workspace_root = workspace_root
        self.app_root = get_settings().app_root
        self.db = SimulationDBHandler(workspace_root)
        self.query_db = self.app_root / "data" / "daemons" / "query_generation" / "queries.db"
        self.results = []

    def load_scenario(self, scenario: SimulationScenario):
        print(f"\n🚀 Running Scenario: {scenario.name}")
        print(f"📝 Description: {scenario.description}")
        
        # Inject Email logs
        for email in scenario.emails:
            self.db.inject_email(
                subject=email.get('subject', ''),
                sender=email.get('sender', ''),
                body=email.get('body', '')
            )
            
        # Inject Browser logs
        for browser in scenario.browser_logs:
            self.db.inject_browser(
                url=browser.get('url', ''),
                title=browser.get('title', '')
            )
            
        # Inject Filesystem logs
        for fs in scenario.fs_logs:
            # If content_preview is not provided, try to read the actual file
            content_preview = fs.get('content_preview', '')
            file_path = fs.get('file_path', '')
            if not content_preview and file_path:
                full_path = self.workspace_root / file_path
                if full_path.exists():
                    try:
                        with open(full_path, 'r') as f:
                            content_preview = f.read(500)  # Read first 500 chars
                    except Exception:
                        pass
            
            self.db.inject_fs(
                action=fs.get('action', 'modified'),
                file_path=file_path,
                content_preview=content_preview
            )

    async def monitor_progress(self, timeout_seconds: int = 120):
        """Monitor queries.db for new queries generated by the daemon."""
        print(f"\n🔍 Monitoring for query generation (timeout: {timeout_seconds}s)...")
        start_time = time.time()
        queries_found = set()
        
        while time.time() - start_time < timeout_seconds:
            try:
                with sqlite3.connect(self.query_db) as conn:
                    cursor = conn.execute("SELECT id, query_text FROM generated_queries WHERE query_text IS NOT NULL")
                    for row in cursor.fetchall():
                        q_id, q_text = row
                        if q_id not in queries_found:
                            print(f"  ✨ [Query Gen] Found: \"{q_text}\"")
                            queries_found.add(q_id)
                            # If we found at least one query, we know Phase 1 worked
            except sqlite3.OperationalError:
                # Database might not be ready yet
                pass
            
            if queries_found:
                # Give it a bit more time to generate other queries if any
                await asyncio.sleep(5)
                # For a simulation, once we have queries, we've verified the generation part
                break
                
            await asyncio.sleep(2)
            
        if not queries_found:
            print("  ⚠️ [Query Gen] No queries found within timeout.")
        else:
            print("  ✅ [Query Gen] Successfully verified query generation.")
            
        return list(queries_found)

    async def run_scenarios(self, scenarios: List[SimulationScenario]):
        self.db.clear_all()
        for scenario in scenarios:
            self.load_scenario(scenario)
            await self.monitor_progress()
        print("\n🏁 Simulation complete.")
